#include "MovingImmersedTransientFlowRuntime.hpp"

#include <algorithm>
#include <array>
#include <cmath>
#include <cstring>
#include <iostream>
#include <stdexcept>
#include <vector>

namespace {
using iga::ImmersedTransientFlowDiagnostics;
using iga::MovingImmersedTransientFlowRuntime;
void Check(bool value,const char* message){if(!value)throw std::runtime_error(message);}
template<class T> bool Bits(const T& a,const T& b){return std::memcmp(&a,&b,sizeof(T))==0;}
template<class T> bool Bits(const std::vector<T>& a,const std::vector<T>& b){return a.size()==b.size()&&(a.empty()||std::memcmp(a.data(),b.data(),a.size()*sizeof(T))==0);}
template<class F> void Reject(F&& f){bool rejected=false;try{f();}catch(const std::exception&){rejected=true;}Check(rejected,"expected rejection");}
iga::RawSurfaceTriangle Face(std::int64_t a,std::int64_t b,std::int64_t c,std::uint32_t label){iga::RawSurfaceTriangle v;v.indices={{a,b,c}};v.boundary_id=label;return v;}
iga::RawSurfaceSoup Cube(double lo,double hi){iga::RawSurfaceSoup v;v.vertices={{{{lo,lo,lo}},{{hi,lo,lo}},{{hi,hi,lo}},{{lo,hi,lo}},{{lo,lo,hi}},{{hi,lo,hi}},{{hi,hi,hi}},{{lo,hi,hi}}}};v.triangles={Face(0,2,1,7),Face(0,3,2,7),Face(4,5,6,7),Face(4,6,7,7),Face(0,1,5,7),Face(0,5,4,7),Face(1,2,6,2),Face(1,6,5,2),Face(2,3,7,7),Face(2,7,6,7),Face(3,0,4,1),Face(3,4,7,1)};return v;}
iga::MovingImmersedTransientFlowOptions Options(double left_target=0.){iga::MovingImmersedTransientFlowOptions v;v.grid={{{0,0,0}},{{1,1,1}},{{3,3,3}}};v.geometry.volume.max_depth=3;v.geometry.volume.max_nodes=v.geometry.volume.max_leaves=v.geometry.volume.max_points=1000000;v.flow.parameters={1.,1.,1.};v.flow.wall_labels={7};v.flow.ports={{"left",1,iga::ImmersedFlowPortControlMode::FlowRate,left_target},{"right",2,iga::ImmersedFlowPortControlMode::FlowRate,-left_target}};v.flow.ksp_relative_tolerance=1e-16;v.flow.lu_pivot_shift=1e-20;v.flow.flow_controller_reference_flow_m3_s=1.;return v;}
iga::MovingImmersedTransientFlowOptions LayoutOptions(double left_target=0.){auto v=Options(left_target);v.grid.cells={{6,6,6}};return v;}
std::vector<std::array<double,4>> Fields(const iga::ImmersedActiveLayout& l){std::vector<std::array<double,4>> v(l.NodeIds().size());for(std::size_t i=0;i<v.size();++i)for(int q=0;q<4;++q)v[i][q]=.01*static_cast<double>(static_cast<int>((7*i+q)%11)-5);return v;}
bool SamePort(const ImmersedTransientFlowDiagnostics::Port&a,const ImmersedTransientFlowDiagnostics::Port&b){return a.id==b.id&&a.boundary_label==b.boundary_label&&a.control_mode==b.control_mode&&Bits(a.target,b.target)&&Bits(a.multiplier,b.multiplier)&&Bits(a.controller_error,b.controller_error)&&a.multiplier_row==b.multiplier_row&&Bits(a.measurement.area_m2,b.measurement.area_m2)&&Bits(a.measurement.outward_flow_m3_s,b.measurement.outward_flow_m3_s)&&Bits(a.measurement.mean_pressure_pa,b.measurement.mean_pressure_pa)&&Bits(a.measurement.mean_normal_traction_pa,b.measurement.mean_normal_traction_pa)&&Bits(a.measurement.mean_velocity_squared_m2_s2,b.measurement.mean_velocity_squared_m2_s2)&&a.measurement_valid==b.measurement_valid;}
bool SamePorts(const std::vector<ImmersedTransientFlowDiagnostics::Port>&a,const std::vector<ImmersedTransientFlowDiagnostics::Port>&b){if(a.size()!=b.size())return false;for(std::size_t i=0;i<a.size();++i)if(!SamePort(a[i],b[i]))return false;return true;}
bool SameNewton(const std::vector<iga::ImmersedTransientFlowNewtonStep>&a,const std::vector<iga::ImmersedTransientFlowNewtonStep>&b){if(a.size()!=b.size())return false;for(std::size_t i=0;i<a.size();++i)if(a[i].iteration!=b[i].iteration||a[i].ksp_iterations!=b[i].ksp_iterations||a[i].ksp_reason!=b[i].ksp_reason||!Bits(a[i].residual_norm,b[i].residual_norm)||!Bits(a[i].update_norm,b[i].update_norm)||!Bits(a[i].linear_relative_residual,b[i].linear_relative_residual)||!Bits(a[i].damping,b[i].damping))return false;return true;}
bool SameInner(const ImmersedTransientFlowDiagnostics&a,const ImmersedTransientFlowDiagnostics&b){return a.active_nodes==b.active_nodes&&a.physical_dofs==b.physical_dofs&&a.total_dofs==b.total_dofs&&a.volume_cells==b.volume_cells&&a.surface_cells==b.surface_cells&&a.ghost_faces==b.ghost_faces&&Bits(a.target_time_s,b.target_time_s)&&Bits(a.dt_s,b.dt_s)&&Bits(a.pressure_measure,b.pressure_measure)&&Bits(a.pressure_gauge_defect,b.pressure_gauge_defect)&&Bits(a.residual_norm,b.residual_norm)&&Bits(a.true_linear_relative_residual,b.true_linear_relative_residual)&&a.nonlinear_iterations==b.nonlinear_iterations&&a.ksp_iterations==b.ksp_iterations&&a.identity_history_nodes==b.identity_history_nodes&&a.committed_history_nodes==b.committed_history_nodes&&a.extended_history_nodes==b.extended_history_nodes&&a.missing_history_nodes==b.missing_history_nodes&&a.ksp_reason==b.ksp_reason&&a.idle==b.idle&&a.trial_active==b.trial_active&&a.converged==b.converged&&a.prepared==b.prepared&&a.committed==b.committed&&a.scalar_diagonal_structure_verified==b.scalar_diagonal_structure_verified&&a.attempt_count==b.attempt_count&&a.abort_count==b.abort_count&&a.rollback_count==b.rollback_count&&a.prepare_count==b.prepare_count&&a.finalize_count==b.finalize_count&&a.commit_count==b.commit_count&&Bits(a.last_assembly_seconds,b.last_assembly_seconds)&&Bits(a.last_linear_solve_seconds,b.last_linear_solve_seconds)&&a.geometry_identity_sha256==b.geometry_identity_sha256&&a.layout_hash_sha256==b.layout_hash_sha256&&a.committed_state_hash_sha256==b.committed_state_hash_sha256&&a.trial_state_hash_sha256==b.trial_state_hash_sha256&&a.history_hash_sha256==b.history_hash_sha256&&a.input_hash_sha256==b.input_hash_sha256&&a.solved_state_hash_sha256==b.solved_state_hash_sha256&&a.prepared_hash_sha256==b.prepared_hash_sha256&&a.attempt_hash_sha256==b.attempt_hash_sha256&&a.moving_map_identity_sha256==b.moving_map_identity_sha256&&a.attempt_assembly_count==b.attempt_assembly_count&&SamePorts(a.ports,b.ports)&&SameNewton(a.newton_steps,b.newton_steps);}
bool SameOuter(const iga::MovingImmersedTransientFlowDiagnostics&a,const iga::MovingImmersedTransientFlowDiagnostics&b){return a.idle==b.idle&&a.trial_active==b.trial_active&&a.prepared==b.prepared&&a.begin_count==b.begin_count&&a.rollback_count==b.rollback_count&&a.abort_count==b.abort_count&&a.prepare_count==b.prepare_count&&a.finalize_count==b.finalize_count&&a.committed_geometry_identity_sha256==b.committed_geometry_identity_sha256&&a.committed_publication_identity_sha256==b.committed_publication_identity_sha256&&a.trial_geometry_identity_sha256==b.trial_geometry_identity_sha256&&a.trial_publication_identity_sha256==b.trial_publication_identity_sha256&&a.extension_hash_sha256==b.extension_hash_sha256&&a.scalar_extension_hash_sha256==b.scalar_extension_hash_sha256&&a.map_identity_sha256==b.map_identity_sha256&&a.transition_identity_sha256==b.transition_identity_sha256;}
struct Snapshot{std::vector<PetscScalar> state;std::string global_hash,geometry,publication,layout_hash;std::vector<std::int32_t>nodes;std::size_t rows;ImmersedTransientFlowDiagnostics diagnostics;};
Snapshot Take(const MovingImmersedTransientFlowRuntime&r){return{r.CommittedState(),r.CommittedGlobalState().HashSha256(),r.CommittedGeometry().GeometryIdentitySha256(),r.CommittedGeometry().PublicationIdentitySha256(),r.CommittedLayout().HashSha256(),r.CommittedLayout().NodeIds(),r.CommittedLayout().Rows(),r.CommittedDiagnostics()};}
void CheckSnapshot(const MovingImmersedTransientFlowRuntime&r,const Snapshot&b){Check(Bits(r.CommittedState(),b.state),"committed vector changed");Check(r.CommittedGlobalState().HashSha256()==b.global_hash,"committed global state changed");Check(r.CommittedGeometry().GeometryIdentitySha256()==b.geometry&&r.CommittedGeometry().PublicationIdentitySha256()==b.publication,"committed geometry/publication changed");Check(r.CommittedLayout().HashSha256()==b.layout_hash&&r.CommittedLayout().NodeIds()==b.nodes&&r.CommittedLayout().Rows()==b.rows,"committed layout changed");Check(SameInner(r.CommittedDiagnostics(),b.diagnostics),"committed diagnostics or ports changed");}
void CheckTransfer(const MovingImmersedTransientFlowRuntime&r,bool expansion){const auto&old=r.CommittedLayout();const auto&target=r.TrialLayout();const auto old_state=r.CommittedState(),seed=r.TrialState();const auto extension=iga::ImmersedVelocityExtension::Build(r.CommittedGeometry(),old,r.CommittedGlobalState(),r.TrialGeometry(),target,3,{});const auto&history=extension.TargetHistory();Check(old.NodeIds()!=target.NodeIds()&&old.Rows()!=target.Rows(),"strict layout transition did not change node IDs/rows");Check(old.ControllerRow(1)!=target.ControllerRow(1),"stable controller row did not move with layout");Check(target.HasGaugeRow(),"target layout lacks pressure gauge");const double target_gauge=PetscRealPart(seed[target.GaugeRow()]);Check(!std::signbit(target_gauge)&&Bits(target_gauge,0.0),"target seed gauge is not canonical positive zero");Check(history.NodeIds()==target.NodeIds()&&extension.HashSha256()==r.Diagnostics().extension_hash_sha256,"target velocity history does not match the published extension");std::size_t old_only=0,new_only=0,overlap=0;for(auto id:old.NodeIds()){if(!std::binary_search(target.NodeIds().begin(),target.NodeIds().end(),id)){++old_only;continue;}const auto oi=old.LocalNode(id),ti=target.LocalNode(id);++overlap;Check(history.Provenance()[ti]==iga::ImmersedVelocityHistoryProvenance::Committed,"overlapping target node is not committed");for(int q=0;q<4;++q)Check(Bits(seed[4*ti+q],old_state[4*oi+q]),"overlapping velocity or pressure seed lost bitwise anchor value");}for(auto id:target.NodeIds())if(!std::binary_search(old.NodeIds().begin(),old.NodeIds().end(),id)){const auto ti=target.LocalNode(id);++new_only;Check(history.Provenance()[ti]==iga::ImmersedVelocityHistoryProvenance::Extended,"newly activated target node is not extended");}const auto&diagnostics=r.TrialDiagnostics();Check(diagnostics.identity_history_nodes==target.NodeIds().size()&&diagnostics.missing_history_nodes==0&&diagnostics.committed_history_nodes==overlap&&diagnostics.extended_history_nodes==new_only,"history provenance diagnostics do not exactly reconcile with target nodes");Check(overlap>0&&old_only>0,"layout fixture lacks the required deactivated overlapping nodes");if(expansion)Check(new_only>0&&diagnostics.extended_history_nodes==new_only,"expansion lacks newly activated extended nodes");else Check(new_only==0&&diagnostics.extended_history_nodes==0&&overlap==target.NodeIds().size(),"contraction target contains non-overlapping extended nodes");Check(Bits(seed[target.ControllerRow(1)],old_state[old.ControllerRow(1)])&&Bits(seed[target.ControllerRow(2)],old_state[old.ControllerRow(2)]),"controller continuation was not bitwise by ID");}
}

int main(int argc,char**argv){PetscInitialize(&argc,&argv,nullptr,nullptr);int status=0;try{
	// Intentional outer-boundary injection seams; the throwing body-force case is a genuine production exception path.
	iga::PrescribedSurfaceMotion contraction_motion({{0.,Cube(.025,.975)},{1.,Cube(.275,.725)}});MovingImmersedTransientFlowRuntime failure_runtime(contraction_motion.Evaluate(0.,0.,1.),Options());failure_runtime.InitializeCommittedGlobalState(iga::ImmersedGlobalFlowState(0.,0,failure_runtime.CommittedLayout(),Fields(failure_runtime.CommittedLayout()),{.021,-.034},true,-0.));const auto failure_before=Take(failure_runtime);const auto failure_outer_before=failure_runtime.Diagnostics();
	const std::array<MovingImmersedTransientFlowRuntime::TestingFault,8> faults{{MovingImmersedTransientFlowRuntime::TestingFault::Geometry,MovingImmersedTransientFlowRuntime::TestingFault::InnerRuntime,MovingImmersedTransientFlowRuntime::TestingFault::Extension,MovingImmersedTransientFlowRuntime::TestingFault::Scalar,MovingImmersedTransientFlowRuntime::TestingFault::Seed,MovingImmersedTransientFlowRuntime::TestingFault::Map,MovingImmersedTransientFlowRuntime::TestingFault::BodyForce,MovingImmersedTransientFlowRuntime::TestingFault::MovingBegin}};
	for(auto fault:faults){MovingImmersedTransientFlowRuntime::TestingFaultScope scope(fault);Reject([&]{failure_runtime.BeginTrial(contraction_motion.Evaluate(1.,0.,1.),1,1.);});Check(failure_runtime.Idle(),"boundary injection published trial");CheckSnapshot(failure_runtime,failure_before);Check(SameOuter(failure_runtime.Diagnostics(),failure_outer_before),"boundary injection changed public outer diagnostics/hashes");}
	auto throwing_options=Options();throwing_options.flow.body_force=[](const std::array<double,3>&)->std::array<double,3>{throw std::runtime_error("body force fault");};MovingImmersedTransientFlowRuntime throwing(contraction_motion.Evaluate(0.,0.,1.),throwing_options);const auto throwing_before=Take(throwing);const auto throwing_outer_before=throwing.Diagnostics();Reject([&]{throwing.BeginTrial(contraction_motion.Evaluate(1.,0.,1.),1,1.);});Check(throwing.Idle(),"throwing production body force published trial");CheckSnapshot(throwing,throwing_before);Check(SameOuter(throwing.Diagnostics(),throwing_outer_before),"production body-force failure changed public outer diagnostics/hashes");
	MovingImmersedTransientFlowRuntime contraction(contraction_motion.Evaluate(0.,0.,1.),LayoutOptions());contraction.InitializeCommittedGlobalState(iga::ImmersedGlobalFlowState(0.,0,contraction.CommittedLayout(),Fields(contraction.CommittedLayout()),{.021,-.034},true,-0.));const auto contraction_before=Take(contraction);contraction.BeginTrial(contraction_motion.Evaluate(1.,0.,1.),1,1.);CheckTransfer(contraction,false);const auto contraction_old=contraction.CommittedLayout().Rows(),contraction_new=contraction.TrialLayout().Rows();contraction.AbortTrial();CheckSnapshot(contraction,contraction_before);
	iga::PrescribedSurfaceMotion expansion_motion({{0.,Cube(.275,.725)},{1.,Cube(.025,.975)}});MovingImmersedTransientFlowRuntime expansion(expansion_motion.Evaluate(0.,0.,1.),LayoutOptions());expansion.InitializeCommittedGlobalState(iga::ImmersedGlobalFlowState(0.,0,expansion.CommittedLayout(),Fields(expansion.CommittedLayout()),{.021,-.034},true,-0.));expansion.BeginTrial(expansion_motion.Evaluate(1.,0.,1.),1,1.);CheckTransfer(expansion,true);const auto expansion_old=expansion.CommittedLayout().Rows(),expansion_new=expansion.TrialLayout().Rows();expansion.AbortTrial();
	// The effective frozen inner input binds port targets into the outer transition identity.
	MovingImmersedTransientFlowRuntime identity_a(contraction_motion.Evaluate(0.,0.,1.),Options(.01)),identity_b(contraction_motion.Evaluate(0.,0.,1.),Options(.02));identity_a.BeginTrial(contraction_motion.Evaluate(1.,0.,1.),1,1.);identity_b.BeginTrial(contraction_motion.Evaluate(1.,0.,1.),1,1.);Check(identity_a.TrialDiagnostics().input_hash_sha256!=identity_b.TrialDiagnostics().input_hash_sha256,"port target perturbation did not change frozen inner input identity");Check(identity_a.Diagnostics().transition_identity_sha256!=identity_b.Diagnostics().transition_identity_sha256,"port target perturbation did not change outer transition identity");identity_a.AbortTrial();identity_b.AbortTrial();
	// Genuine zero-solution epoch: stationary coordinates, zero state/body force/ports, positive dt, and real SolveTrial.
	iga::PrescribedSurfaceMotion stationary_motion({{0.,Cube(.10,.90)},{2.,Cube(.10,.90)},{3.,Cube(.10,.90)}});MovingImmersedTransientFlowRuntime stationary(stationary_motion.Evaluate(0.,0.,1.),Options());const auto zero_before=Take(stationary);stationary.BeginTrial(stationary_motion.Evaluate(1.,0.,1.),1,1.);Check(stationary.SolveTrial(),"real stationary zero solve did not converge");const auto solved_state=stationary.TrialState();const auto solved=stationary.TrialDiagnostics();const auto solved_outer=stationary.Diagnostics();stationary.FailNextPrepareForTesting();Reject([&]{stationary.PrepareCommit();});Check(!stationary.Prepared(),"failed prepare published prepared outer epoch");Check(Bits(stationary.TrialState(),solved_state)&&SameInner(stationary.TrialDiagnostics(),solved),"failed prepare changed solved trial state/diagnostics");Check(SameOuter(stationary.Diagnostics(),solved_outer),"failed prepare changed public outer diagnostics/hashes");CheckSnapshot(stationary,zero_before);
	stationary.PrepareCommit();Check(stationary.Prepared(),"real prepare did not publish prepared trial");Check(stationary.TrialDiagnostics().input_hash_sha256==solved.input_hash_sha256&&stationary.TrialDiagnostics().attempt_hash_sha256==solved.attempt_hash_sha256&&stationary.TrialDiagnostics().solved_state_hash_sha256==solved.solved_state_hash_sha256&&stationary.TrialDiagnostics().attempt_assembly_count==solved.attempt_assembly_count&&SameNewton(stationary.TrialDiagnostics().newton_steps,solved.newton_steps),"prepare retry changed solved attempt identity/work");CheckSnapshot(stationary,zero_before);const auto target_geometry=stationary.TrialGeometry().GeometryIdentitySha256(),target_publication=stationary.TrialGeometry().PublicationIdentitySha256(),target_layout=stationary.TrialLayout().HashSha256(),prepared_hash=stationary.TrialDiagnostics().prepared_hash_sha256;stationary.FinalizeCommit();Check(stationary.Idle()&&!stationary.Prepared(),"finalize did not atomically leave idle");Check(stationary.CommittedGeometry().GeometryIdentitySha256()==target_geometry&&stationary.CommittedGeometry().PublicationIdentitySha256()==target_publication&&stationary.CommittedLayout().HashSha256()==target_layout&&stationary.CommittedGlobalState().TimeS()==1.&&stationary.CommittedGlobalState().Index()==1&&stationary.CommittedDiagnostics().committed_state_hash_sha256==stationary.CommittedGlobalState().HashSha256()&&!prepared_hash.empty(),"finalize did not promote target epoch atomically");
	const auto committed_after_finalize=Take(stationary);stationary.BeginTrial(stationary_motion.Evaluate(1.5,1.,1.5),2,.5);Check(stationary.SolveTrial(),"second real stationary solve did not converge");stationary.PrepareCommit();Check(stationary.Prepared(),"second real prepare did not publish");stationary.AbortPrepared();Check(stationary.Idle()&&!stationary.Prepared(),"abort prepared was not noexcept owner discard");CheckSnapshot(stationary,committed_after_finalize);
	std::cout<<"moving_immersed_transient_flow_tests=passed contraction_rows=(old="<<contraction_old<<",new="<<contraction_new<<") expansion_rows=(old="<<expansion_old<<",new="<<expansion_new<<")\n"<<std::flush;
}catch(const std::exception&e){std::cerr<<"moving_immersed_transient_flow_test: "<<e.what()<<'\n';status=1;}PetscFinalize();return status;}
