# Target and test helpers shared by every directory.
#
# Executables are written beside their sources (for example solvers/cpu/iga_solve)
# so that scripts, documentation, and evidence commands keep resolving them.
# Objects and generated files stay in the build tree.
#
# Each directory sets TFI_DIRECTORY_INCLUDES and TFI_DIRECTORY_OPTIONS before
# declaring targets. The bookkeeping recorded here is written to
# <build>/tfi-forward.json, which the per-directory Makefiles use to keep every
# historical `make -C <dir> <target>` command working.
include_guard(GLOBAL)

function(_tfi_directory_key out)
	file(RELATIVE_PATH directory "${PROJECT_SOURCE_DIR}" "${CMAKE_CURRENT_SOURCE_DIR}")
	string(REPLACE "/" "__" key "${directory}")
	set_property(GLOBAL APPEND PROPERTY TFI_DIRECTORIES "${directory}")
	set(${out} "${key}" PARENT_SCOPE)
endfunction()

# Record a target that cannot be built in this configuration.
function(tfi_skip_target name reason)
	_tfi_directory_key(key)
	set_property(GLOBAL APPEND PROPERTY TFI_${key}_SKIPPED "${name}=${reason}")
	set_property(GLOBAL PROPERTY TFI_SKIPPED_${name} "${reason}")
endfunction()

function(_tfi_missing_dependency out)
	set(reason "")
	foreach(requirement IN LISTS ARGN)
		if(requirement STREQUAL "PETSC" AND NOT TARGET TubularFlow::PETSc)
			set(reason "PETSc (pass PETSC_DIR and PETSC_ARCH)")
		elseif(requirement STREQUAL "HDF5" AND NOT TARGET TubularFlow::HDF5)
			set(reason "HDF5")
		elseif(requirement STREQUAL "MPI" AND NOT TARGET MPI::MPI_CXX)
			set(reason "MPI")
		elseif(requirement STREQUAL "OPENMP" AND NOT TARGET OpenMP::OpenMP_CXX)
			set(reason "OpenMP")
		elseif(requirement STREQUAL "CUDA" AND NOT TFI_ENABLE_CUDA)
			set(reason "CUDA (configure with TFI_ENABLE_CUDA=ON or run `make cuda`)")
		endif()
	endforeach()
	set(${out} "${reason}" PARENT_SCOPE)
endfunction()

# tfi_executable(<name> SOURCES <file>...
#   [PETSC] [MPI] [HDF5] [OPENMP] [CUDA] [NATIVE_CHECKPOINT_IDENTITY]
#   [DEFINITIONS <name[=value]>...] [OPTIONS <flag>...] [INCLUDES <dir>...]
#   [LINK_OPTIONS <flag>...] [LIBRARIES <lib>...])
function(tfi_executable name)
	cmake_parse_arguments(PARSE_ARGV 1 arg
		"PETSC;MPI;HDF5;OPENMP;CUDA;NATIVE_CHECKPOINT_IDENTITY" ""
		"SOURCES;DEFINITIONS;OPTIONS;INCLUDES;LINK_OPTIONS;LIBRARIES")
	set(requirements)
	foreach(flag PETSC MPI HDF5 OPENMP CUDA)
		if(arg_${flag})
			list(APPEND requirements ${flag})
		endif()
	endforeach()
	_tfi_missing_dependency(reason ${requirements})
	if(reason)
		tfi_skip_target(${name} "${reason}")
		return()
	endif()
	add_executable(${name} ${arg_SOURCES})
	target_include_directories(${name} PRIVATE ${TFI_DIRECTORY_INCLUDES} ${arg_INCLUDES})
	target_compile_options(${name} PRIVATE
		$<$<COMPILE_LANGUAGE:CXX>:${TFI_DIRECTORY_OPTIONS}> ${arg_OPTIONS})
	target_compile_definitions(${name} PRIVATE ${arg_DEFINITIONS})
	target_link_options(${name} PRIVATE ${arg_LINK_OPTIONS})
	target_link_libraries(${name} PRIVATE ${arg_LIBRARIES})
	if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS 9.1)
		target_link_libraries(${name} PRIVATE stdc++fs)
	endif()
	if(arg_PETSC)
		target_link_libraries(${name} PRIVATE TubularFlow::PETSc)
	endif()
	if(arg_MPI)
		target_link_libraries(${name} PRIVATE MPI::MPI_CXX)
	endif()
	if(arg_HDF5)
		target_link_libraries(${name} PRIVATE TubularFlow::HDF5)
	endif()
	if(arg_OPENMP)
		target_link_libraries(${name} PRIVATE OpenMP::OpenMP_CXX)
	endif()
	if(arg_NATIVE_CHECKPOINT_IDENTITY)
		add_dependencies(${name} tfi_native_checkpoint_identity)
		target_compile_options(${name} PRIVATE -include "${TFI_NATIVE_CHECKPOINT_IDENTITY_HEADER}")
	endif()
	if(arg_CUDA)
		# nvcc's library directory counts as implicit, so CMake adds no RPATH
		# for cuBLAS/cuSOLVER; a Conda toolkit would then need LD_LIBRARY_PATH.
		set_target_properties(${name} PROPERTIES BUILD_RPATH "${CUDAToolkit_LIBRARY_DIR}")
	endif()
	_tfi_directory_key(key)
	set_property(GLOBAL APPEND PROPERTY TFI_${key}_TARGETS ${name})
	set_target_properties(${name} PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}")
endfunction()

# A preloadable shared object used by failure-injection tests (no lib prefix).
function(tfi_preload_library name)
	cmake_parse_arguments(PARSE_ARGV 1 arg "MPI" "" "SOURCES;LIBRARIES")
	if(arg_MPI AND NOT TARGET MPI::MPI_CXX)
		tfi_skip_target(${name} "MPI")
		return()
	endif()
	add_library(${name} MODULE ${arg_SOURCES})
	target_compile_options(${name} PRIVATE -Wall -Wextra -Wpedantic)
	target_link_libraries(${name} PRIVATE ${arg_LIBRARIES})
	if(arg_MPI)
		target_link_libraries(${name} PRIVATE MPI::MPI_CXX)
	endif()
	string(REGEX REPLACE "\\.so$" "" output "${name}")
	set_target_properties(${name} PROPERTIES PREFIX "" OUTPUT_NAME "${output}"
		LIBRARY_OUTPUT_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}")
	_tfi_directory_key(key)
	set_property(GLOBAL APPEND PROPERTY TFI_${key}_TARGETS ${name})
	set_property(GLOBAL PROPERTY TFI_OUTPUT_${name} "${output}.so")
endfunction()

# tfi_test(<name> COMMAND <shell command> REQUIRES <target>... [MAKE <make target>...] [LABELS <label>...])
#
# The command runs with `sh -c` in the source directory, exactly as the former
# Makefile recipe did, but with a private TMPDIR (see run_test.sh). @TFI_PETSC_PREFIX@ and @TFI_MPIEXEC@ are substituted at
# configure time; shell variables such as ${MPI_TEST_RANKS:-2} stay overridable.
function(tfi_test name)
	cmake_parse_arguments(PARSE_ARGV 1 arg "" "COMMAND" "REQUIRES;MAKE;LABELS")
	_tfi_directory_key(key)
	get_filename_component(directory_label "${CMAKE_CURRENT_SOURCE_DIR}" NAME)
	set(reason "")
	foreach(required IN LISTS arg_REQUIRES)
		if(NOT TARGET ${required})
			get_property(reason GLOBAL PROPERTY TFI_SKIPPED_${required})
			if(NOT reason)
				message(FATAL_ERROR "test ${name} requires unknown target ${required}")
			endif()
			break()
		endif()
	endforeach()
	foreach(make_target IN LISTS arg_MAKE)
		set_property(GLOBAL APPEND PROPERTY TFI_${key}_MAKE ${make_target})
		set_property(GLOBAL APPEND PROPERTY TFI_${key}_MAKE_BUILD_${make_target} ${arg_REQUIRES})
		if(reason)
			set_property(GLOBAL APPEND PROPERTY TFI_${key}_MAKE_SKIPPED_${make_target} "${name}: ${reason}")
		endif()
	endforeach()
	if(reason)
		return()
	endif()
	string(CONFIGURE "${arg_COMMAND}" command @ONLY)
	set(test_name "${directory_label}.${name}")
	add_test(NAME ${test_name} COMMAND sh "${PROJECT_SOURCE_DIR}/cmake/run_test.sh" "${command}"
		WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}")
	set(labels ${directory_label} ${arg_LABELS})
	foreach(make_target IN LISTS arg_MAKE)
		list(APPEND labels "make=${make_target}")
	endforeach()
	set_tests_properties(${test_name} PROPERTIES LABELS "${labels}")
endfunction()

# tfi_make_alias(<make target> TARGETS <target>...): a build-only aggregate such
# as `all` or `petsc` in the historical Makefile.
function(tfi_make_alias alias)
	cmake_parse_arguments(PARSE_ARGV 1 arg "" "" "TARGETS")
	_tfi_directory_key(key)
	set_property(GLOBAL APPEND PROPERTY TFI_${key}_ALIASES ${alias})
	set_property(GLOBAL APPEND PROPERTY TFI_${key}_ALIAS_${alias} ${arg_TARGETS})
endfunction()

function(_tfi_json_array out)
	set(json "[]")
	set(index 0)
	foreach(item IN LISTS ARGN)
		string(JSON json SET "${json}" ${index} "\"${item}\"")
		math(EXPR index "${index} + 1")
	endforeach()
	set(${out} "${json}" PARENT_SCOPE)
endfunction()

# Write <build>/tfi-forward.json for the per-directory forwarding Makefiles.
# A goal that builds several targets gets one umbrella target: `cmake --build`
# runs multiple --target arguments one after another, whereas the dependencies
# of a single target are built in parallel.
function(_tfi_goal_target json key goal)
	set(members)
	foreach(member IN LISTS ARGN)
		if(TARGET ${member})
			list(APPEND members ${member})
		endif()
	endforeach()
	list(LENGTH members count)
	if(count GREATER 1)
		set(umbrella "tfi-goal.${key}.${goal}")
		if(NOT TARGET ${umbrella})
			add_custom_target(${umbrella})
			add_dependencies(${umbrella} ${members})
		endif()
		string(JSON ${json} SET "${${json}}" "${goal}" "\"${umbrella}\"")
		set(${json} "${${json}}" PARENT_SCOPE)
	endif()
endfunction()

function(tfi_write_forward_manifest)
	get_property(directories GLOBAL PROPERTY TFI_DIRECTORIES)
	list(REMOVE_DUPLICATES directories)
	set(manifest "{}")
	foreach(directory IN LISTS directories)
		string(REPLACE "/" "__" key "${directory}")
		set(entry "{}")
		get_property(targets GLOBAL PROPERTY TFI_${key}_TARGETS)
		set(outputs)
		foreach(target IN LISTS targets)
			get_property(output GLOBAL PROPERTY TFI_OUTPUT_${target})
			if(NOT output)
				set(output "${target}")
			endif()
			list(APPEND outputs "${output}")
		endforeach()
		_tfi_json_array(json ${targets})
		string(JSON entry SET "${entry}" targets "${json}")
		_tfi_json_array(json ${outputs})
		string(JSON entry SET "${entry}" outputs "${json}")
		get_property(skipped GLOBAL PROPERTY TFI_${key}_SKIPPED)
		set(skipped_json "{}")
		foreach(item IN LISTS skipped)
			# Split at the first "=" only; reasons may contain "=" themselves.
			string(FIND "${item}" "=" split)
			string(SUBSTRING "${item}" 0 ${split} target)
			math(EXPR split "${split}+1")
			string(SUBSTRING "${item}" ${split} -1 reason)
			string(JSON skipped_json SET "${skipped_json}" "${target}" "\"${reason}\"")
		endforeach()
		string(JSON entry SET "${entry}" skipped "${skipped_json}")
		set(goals_json "{}")
		set(aliases_json "{}")
		get_property(aliases GLOBAL PROPERTY TFI_${key}_ALIASES)
		foreach(alias IN LISTS aliases)
			get_property(members GLOBAL PROPERTY TFI_${key}_ALIAS_${alias})
			_tfi_json_array(json ${members})
			string(JSON aliases_json SET "${aliases_json}" "${alias}" "${json}")
			_tfi_goal_target(goals_json ${key} ${alias} ${members})
		endforeach()
		string(JSON entry SET "${entry}" aliases "${aliases_json}")
		set(make_json "{}")
		get_property(make_targets GLOBAL PROPERTY TFI_${key}_MAKE)
		list(REMOVE_DUPLICATES make_targets)
		foreach(make_target IN LISTS make_targets)
			get_property(build GLOBAL PROPERTY TFI_${key}_MAKE_BUILD_${make_target})
			list(REMOVE_DUPLICATES build)
			get_property(missing GLOBAL PROPERTY TFI_${key}_MAKE_SKIPPED_${make_target})
			_tfi_json_array(build_json ${build})
			_tfi_json_array(missing_json ${missing})
			string(JSON make_json SET "${make_json}" "${make_target}"
				"{\"build\":${build_json},\"skipped\":${missing_json}}")
			_tfi_goal_target(goals_json ${key} ${make_target} ${build})
		endforeach()
		string(JSON entry SET "${entry}" tests "${make_json}")
		string(JSON entry SET "${entry}" goals "${goals_json}")
		string(JSON manifest SET "${manifest}" "${directory}" "${entry}")
	endforeach()
	file(WRITE "${CMAKE_BINARY_DIR}/tfi-forward.json" "${manifest}\n")
endfunction()
